#!/bin/bash

echo "=== INSTRUCCIONES PARA PROBAR EL RENDIMIENTO DEL SERVIDOR ==="
echo ""
echo "1. Para iniciar el servidor con 8 threads:"
echo "   java WebServer2 8080 8"
echo ""
echo "2. Para iniciar el servidor con 1 thread:"
echo "   java WebServer2 8080 1"
echo ""
echo "3. Para probar con curl desde otra terminal:"
echo "   time curl -X POST -d '123,456' http://localhost:8080/task"
echo ""
echo "4. Para ejecutar dos curl simultáneamente en terminales separadas:"
echo "   Terminal 1: time curl -X POST -d '123,456' http://localhost:8080/task"
echo "   Terminal 2: time curl -X POST -d '789,101' http://localhost:8080/task"
echo ""
echo "=== DATOS PARA LA PRUEBA ==="
echo "- El servidor ahora tiene un sleep de 5 segundos en cada tarea"
echo "- Con 8 threads: las dos peticiones se procesarán en paralelo (~5 segundos cada una)"
echo "- Con 1 thread: las peticiones se procesarán secuencialmente (~5 segundos la primera, ~10 segundos la segunda)"
echo ""
